#!/usr/bin/env bash

set -e

if [ $# -ne 1 ]; then
    echo "Usage: $0 <program.tiff>"
    exit 1
fi

mkdir -p outputs
mkdir -p servicelog

PROGRAMTIFF="$1"

convert $PROGRAMTIFF -resize 2100x2970\! temp.tif

tiffname=$(basename $PROGRAMTIFF)
logdir="servicelog/$tiffname"
mkdir -p "$logdir"
cp temp.tif "$logdir/$tiffname"



PROGRAM="ocr_result.c"
#tesseract temp.tif "$PROGRAM" --psm 6 --user-words CCode tessconfig
tesseract temp.tif "$PROGRAM" --psm 6 tessconfig
clang-format --style=mozilla < "$PROGRAM.txt" > "$PROGRAM"

SENDER=$(./find_sender $PROGRAM)
if [ "x$SENDER" == "x" ]; then
    echo "No sender detected"
    exit 1
fi

DESTPROG="alpine_root/workdir/program.c"

cp "$PROGRAM" "$DESTPROG"
chown $OUTERUSER:$OUTERUSER "$DESTPROG"

echo "" > outputs/program_stderr
echo "" > outputs/program_stdout
set +e
COMPSTART=$(date --rfc-3339=seconds)
timeout -s KILL 10 ./with_chroot 'gcc program.c -o program' 2> outputs/compilation_stderr > outputs/compilation_stdout
COMPILE_RC=$?
COMPEND=$(date --rfc-3339=seconds)
if [ $COMPILE_RC -eq 0 ]; then
    PROGSTART=$(date --rfc-3339=seconds)
    timeout -s KILL 60 ./with_chroot ./program 2> outputs/program_stderr > outputs/program_stdout
    PROGRAM_RC=$?
    PROGEND=$(date --rfc-3339=seconds)
fi

set -e

REQ="outputs/request"
echo "Request from '$SENDER' to compile and run C code" > $REQ
echo "---- Program listing follows ----" >> $REQ
./line_numbers $PROGRAM >> $REQ

SUM="outputs/summary"
if [ $COMPILE_RC -eq 0 ]; then
    echo "Compilation successful" > $SUM
    if [ $PROGRAM_RC -eq 0 ]; then
        echo "Program execution successful" >> $SUM
    else
        echo "Program failed with exit code $PROGRAM_RC" >> $SUM
    fi
else
    echo "Compilation failed with exit code $COMPILE_RC" > $SUM
fi

echo "Compilation started at $COMPSTART" >> $SUM
echo "Compilation ended at   $COMPEND" >> $SUM
if [ $COMPILE_RC -eq 137 ]; then
    echo "Compilation was terminated by timeout" >> $SUM
fi
if [ $COMPILE_RC -eq 0 ]; then
    echo "Program execution started at $PROGSTART" >> $SUM
    echo "Program execution ended at   $PROGEND" >> $SUM
    if [ $PROGRAM_RC -eq 137 ]; then
        echo "Program execution was terminated by timeout" >> $SUM
    fi
fi

echo Run complete, generating response PDF...
./build_document
ps2pdf result.ps result.pdf
cp result.pdf "$logdir/result.pdf"
echo Sending fax...
sendfax -n -f "$FAXID" -d "$SENDER" result.pdf
echo Complete

