#!/usr/bin/env python3

import sys
import re

with open(sys.argv[1]) as f:
    text = f.read();
    for line in text.upper().split('\n'):
        m = re.search("REPLY *= *([0-9 ]+)#", line)
        if m:
            print(m.group(1))
            break
