#!/usr/bin/env bash

set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 <host_low_username> <arch>"
    exit 1
fi

MIRROR='https://uk.alpinelinux.org/alpine/latest-stable/main'
ARCH=$2
APKPKG='apk-tools-static-2.14.4-r0.apk'
OUTERUSER=$1

mkdir alpine_root
curl -LO "$MIRROR/$ARCH/$APKPKG"
tar -xzf "$APKPKG"
./sbin/apk.static -X "$MIRROR" -U --allow-untrusted -p alpine_root/ --initdb add alpine-base build-base || true
mkdir alpine_root/workdir
cp startup alpine_root/workdir
cp capture_the_flag_inner alpine_root/workdir/capture_the_flag
chown -R root:root alpine_root
chown $OUTERUSER:$OUTERUSER alpine_root/workdir
