#!/usr/bin/env python3

import os
import sys
import time
import subprocess
d = sys.argv[1]

while True:
    all_files = [f for f in sorted(os.listdir(d)) if f != 'seqf']
    if len(all_files) > 0:
        f = all_files[0]
        print(f"Process file {f}")
        subprocess.run(['./build_and_run', f])
        os.unlink(os.path.join(d, f))
        continue
    time.sleep(5)
        
