#!/usr/bin/env bash

ROOT=$PWD/alpine_root
OUTERUID=$(id -u $OUTERUSER)
echo $OUTERUSER=$OUTERUID
echo env -i unshare -imnpuUCT --map-root --map-users 500:$OUTERUID:1 --map-groups 500:$UID:1 -R alpine_root -S 500 --wd /workdir /workdir/startup "$@"
env -i unshare -imnpuUCT --map-root --map-users 500:$OUTERUID:1 --map-groups 500:$UID:1 -R alpine_root -S 500 --wd /workdir /workdir/startup "$@"
